// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the sprawling contributors

//! Single embed point: gzips the web client bundle into OUT_DIR and
//! generates `client_embed.rs`, the file table main.rs includes.
//!
//! The bundle is whatever `just build-web` left in `target/web-dist`,
//! plus the page shell from `crates/web/assets/index.html`. When the
//! wasm artifacts are absent the binary still builds - it carries the
//! shell alone, `CLIENT_COMPLETE` is false, and a warning says so -
//! because `just check` must not demand a wasm toolchain. The release
//! gate (`xtask budget`) refuses a release binary whose file table has
//! no `web_bg.wasm`, so an incomplete client cannot ship silently.
//!
//! Gzip is deterministic here: fixed compression level, zeroed mtime.
//! The same source bytes embed identically on every build, which the
//! reproducible-build fixture (`cargo xtask repro`) relies on.

use std::io::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    if let Err(msg) = embed() {
        // cargo >= 1.84: `cargo::error` fails the build loudly instead of
        // leaving a stale or missing asset for include_bytes! to trip on.
        println!("cargo::error=web asset embed failed: {msg}");
    }
}

fn embed() -> Result<(), String> {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").map_err(|e| e.to_string())?;
    let out_dir = std::env::var("OUT_DIR").map_err(|e| e.to_string())?;
    let shell = PathBuf::from(&manifest)
        .join("..")
        .join("web")
        .join("assets")
        .join("index.html");
    println!("cargo::rerun-if-changed={}", shell.display());

    // target/web-dist, robust to profile dirs: walk up from OUT_DIR to the
    // directory literally named `target`, falling back to ../../target.
    let dist = target_dir(&out_dir, &manifest).join("web-dist");
    // Emitted even when absent: the first `just build-web` after a
    // placeholder build must trigger a re-embed, not wait for luck.
    println!("cargo::rerun-if-changed={}", dist.display());

    // (request path, source file) - index.html always, the bundle when built.
    let mut files: Vec<(String, PathBuf)> = vec![("index.html".to_owned(), shell)];
    let mut complete = false;
    if dist.join("web.js").is_file() && dist.join("web_bg.wasm").is_file() {
        complete = true;
        collect(&dist, &dist, &mut files)?;
    } else {
        println!(
            "cargo::warning=web client artifacts not found in {}; the binary will carry the \
             page shell only - run `just build-web`, then rebuild",
            dist.display()
        );
    }
    files.sort_by(|a, b| a.0.cmp(&b.0));

    let web_out = PathBuf::from(&out_dir).join("web");
    let mut table = String::new();
    for (rel, source) in &files {
        println!("cargo::rerun-if-changed={}", source.display());
        let bytes = std::fs::read(source).map_err(|e| format!("{}: {e}", source.display()))?;
        let gz_path = web_out.join(format!("{}.gz", rel.replace('/', "_")));
        if let Some(parent) = gz_path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        let gz = gzip(&bytes)?;
        std::fs::write(&gz_path, gz).map_err(|e| format!("{}: {e}", gz_path.display()))?;
        table.push_str(&format!(
            "    channels::EmbeddedFile {{ path: {rel:?}, gz: include_bytes!({:?}) }},\n",
            gz_path.display().to_string().replace('\\', "/")
        ));
    }

    embed_dependency_list(&manifest, &out_dir)?;

    let generated = format!(
        "// Generated by build.rs; the authority is the file table it read.\n\
         /// Whether the wasm client is inside this binary, or only the shell.\n\
         pub const CLIENT_COMPLETE: bool = {complete};\n\
         /// Every file the browser may request, gzipped at build time.\n\
         pub static CLIENT_FILES: &[channels::EmbeddedFile] = &[\n{table}];\n"
    );
    std::fs::write(PathBuf::from(&out_dir).join("client_embed.rs"), generated)
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// The embedded dependency list (release item: the binary can name what
/// it is made of). Parsed from Cargo.lock with a ten-line reader rather
/// than a toml dependency: the lockfile's [[package]] blocks are stable,
/// machine-written lines.
fn embed_dependency_list(manifest: &str, out_dir: &str) -> Result<(), String> {
    let lock = PathBuf::from(manifest)
        .join("..")
        .join("..")
        .join("Cargo.lock");
    println!("cargo::rerun-if-changed={}", lock.display());
    let text = std::fs::read_to_string(&lock).map_err(|e| format!("{}: {e}", lock.display()))?;
    let mut deps = Vec::new();
    let mut name: Option<String> = None;
    for line in text.lines() {
        if line == "[[package]]" {
            name = None;
        } else if let Some(raw) = line.strip_prefix("name = \"") {
            name = raw.strip_suffix('"').map(str::to_owned);
        } else if let Some(raw) = line.strip_prefix("version = \"")
            && let (Some(package), Some(version)) = (name.take(), raw.strip_suffix('"'))
        {
            deps.push(format!("{package} {version}"));
        }
    }
    deps.sort();
    std::fs::write(
        PathBuf::from(out_dir).join("deps.txt"),
        format!("{}\n", deps.join("\n")),
    )
    .map_err(|e| e.to_string())
}

/// Walks `dist` recursively, recording each file under its request path.
fn collect(root: &Path, dir: &Path, files: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    let entries = std::fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| e.to_string())?;
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, files)?;
            continue;
        }
        let rel = path
            .strip_prefix(root)
            .map_err(|e| e.to_string())?
            .to_string_lossy()
            .replace('\\', "/");
        files.push((rel, path));
    }
    Ok(())
}

fn target_dir(out_dir: &str, manifest: &str) -> PathBuf {
    let mut cursor = PathBuf::from(out_dir);
    while cursor.pop() {
        if cursor.file_name().is_some_and(|n| n == "target") {
            return cursor;
        }
    }
    PathBuf::from(manifest).join("..").join("..").join("target")
}

/// Deterministic gzip: fixed level, zeroed mtime.
fn gzip(bytes: &[u8]) -> Result<Vec<u8>, String> {
    let mut encoder = flate2::GzBuilder::new()
        .mtime(0)
        .write(Vec::new(), flate2::Compression::best());
    encoder.write_all(bytes).map_err(|e| e.to_string())?;
    encoder.finish().map_err(|e| e.to_string())
}
